channel: "slack"
triggers:
  new_item:
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "title"
          operation: "within"
          value: "foo"
      configs:
        - channel: "foo"
    - conditions:
        - type: "level"
          operation: "eq"
          value: "critical"
        - type: "title"
          operation: "within"
          value: "bar"
      configs:
        - channel: "bar"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "title"
          operation: "within"
          value: "baz"
      configs:
        - channel: "baz"
    - conditions:
        - type: "level"
          operation: "eq"
          value: "warning"
        - type: "title"
          operation: "within"
          value: "qux"
      configs:
        - channel: "qux"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "warning"
        - type: "title"
          operation: "within"
          value: "quux"
      configs:
        - channel: "quux"
    - conditions:
        - type: "title"
          operation: "within"
          value: "corge"
      configs:
        - channel: "corge"
