channel: "slack"
triggers:
  new_item:
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "path"
          path: "body.body.trace.extra.a"
          operation: "eq"
          value: "foo"
      configs:
        - channel: "foo"
    - conditions:
        - type: "level"
          operation: "eq"
          value: "critical"
        - type: "path"
          path: "body.body.trace.extra.b"
          operation: "eq"
          value: "bar"
      configs:
        - channel: "bar"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "path"
          path: "body.body.trace.extra.a"
          operation: "eq"
          value: "baz"
      configs:
        - channel: "baz"
    - conditions:
        - type: "level"
          operation: "eq"
          value: "warning"
        - type: "path"
          path: "body.body.trace.extra.c"
          operation: "eq"
          value: "qux"
      configs:
        - channel: "qux"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "warning"
        - type: "path"
          path: "body.body.trace.extra.d"
          operation: "eq"
          value: "quux"
      configs:
        - channel: "quux"
  occurrence_rate:
    - conditions:
        - type: "rate"
          count: 10
          period: 300
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "path"
          path: "body.body.trace.extra.a"
          operation: "eq"
          value: "foo"
      configs:
        - channel: "foo"
    - conditions:
        - type: "rate"
          count: 10
          period: 300
        - type: "level"
          operation: "eq"
          value: "critical"
        - type: "path"
          path: "body.body.trace.extra.b"
          operation: "eq"
          value: "bar"
      configs:
        - channel: "bar"
