channel: "slack"
triggers:
  new_item:
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "path"
          path: "body.body.trace.extra.a"
          operation: "within"
          value: "foo"
        - type: "path"
          path: "body.body.trace.extra.b"
          operation: "within"
          value: "bar"
      configs:
        - channel: "foo-and-bar"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "path"
          path: "body.body.trace.extra.a"
          operation: "within"
          value: "foo"
      configs:
        - channel: "foo"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
