channel: "slack"
triggers:
  new_item:
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "path"
          path: "body.body.trace.extra.a"
          operation: "eq"
          value: "foo"
    - conditions:
        - type: "level"
          operation: "eq"
          value: "critical"
        - type: "path"
          path: "body.body.trace.extra.b"
          operation: "eq"
          value: "bar"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "error"
        - type: "path"
          path: "body.body.trace.extra.a"
          operation: "eq"
          value: "baz"
    - conditions:
        - type: "level"
          operation: "eq"
          value: "warning"
        - type: "path"
          path: "body.body.trace.extra.c"
          operation: "eq"
          value: "qux"
    - conditions:
        - type: "level"
          operation: "gte"
          value: "warning"
        - type: "path"
          path: "body.body.trace.extra.d"
          operation: "eq"
          value: "quux"
