#!/usr/bin/env ruby
require "optparse"

require "rollbar/notification"

FORMATS = %w[terraform text]

opts = { format: "terraform" }
opt_parser = OptionParser.new do |opt|
  opt.banner = "Usage: #{File.basename(__FILE__)} [options] <input>"
  opt.on("--format FORMAT", FORMATS, "#{FORMATS.join("|")} (default: #{opts[:format]})")
end

begin
  opt_parser.parse!(into: opts)
rescue OptionParser::ParseError => e
  $stderr.puts "Error: #{e.message}\n\n"
  $stderr.puts opt_parser.help
  exit 1
end

input = ARGV[0]
unless input
  $stderr.puts opt_parser.help
  exit 1
end

notification = Rollbar::Notification.new(input)
case opts[:format]
when "terraform"
  puts notification.to_tf
when "text"
  puts notification.to_s
end
