name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.3'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Check if defs.rbs is up-to-date
      run: bundle exec rake generate_rbs && git diff --exit-code
    - name: Run the default task
      run: RUBYOPT='-rbundler/setup -rrbs/test/setup' RBS_TEST_TARGET='Rollbar::*' bundle exec rake
